### PR TITLE
arrgh, well i guess centurylink thinks i'm a moron.

### PR DESCRIPTION
**Pull request by jyehbrightcove**
my bash scripting is not strong, there may be a cleaner way to do this.

### CODE REVIEW

**Comment by brycefisher** [comment]
Pull #1! Congrats

**Comment by brycefisher** [comment]
This looks right to me...I'd like to pull it down locally and run it to make sure its right before i lgtm.

**Comment by brycefisher** [comment]
It would be great to add some documentation in the README

**Comment by jyehbrightcove** [comment]
Ah yeah, good point.

**Comment by stuarthicks** [comment]
@brycefisher @jyehbrightcove is this PR going anywhere or can we just close it?

**Comment by brycefisher** [comment]
This is part of the debug effor for sporadic 503 issues from the jit. We need this, but we need to find time to wire up this to quay and swap it into our deployment pipeline.

**Comment by GeneticGenesis** [comment]
I don't think we need this right now.

**Pull request closed without merging**
